name: Backend CI

on:
  push:
    branches: [ main ]

concurrency:
  group: backend-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test_deploy:
    runs-on: self-hosted
    timeout-minutes: 30
    environment:
       name: MONGO_URI

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Yarn via Corepack
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate
          yarn --version

      - name: Setup Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: |
            backend/yarn.lock
            frontend/yarn.lock

      - name: Ensure PM2 installed
        run: |
          if ! command -v pm2 >/dev/null 2>&1; then npm i -g pm2; fi
          pm2 -v

      # ===== Backend =====
      - name: Create backend .env from secrets
        working-directory: ./backend
        run: |
          cat > .env <<'EOF'
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          PORT=${{ secrets.PORT }}
          EOF

      - name: Install backend deps
        working-directory: ./backend
        run: yarn install --frozen-lockfile

      - name: Test backend (if present)
        working-directory: ./backend
        env:
          NODE_ENV: test
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: yarn test --if-present

      # ===== Frontend =====
      - name: Install frontend deps
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Build frontend
        working-directory: ./frontend
        run: yarn build

      # ===== Deploy with PM2（明示的に起動定義）=====
      - name: Stop old PM2 apps (safe)
        run: |
          pm2 delete Frontend || true
          pm2 delete backend  || true

      - name: Start Frontend (static) on 3000
        working-directory: ./frontend
        run: pm2 serve ./build 3000 --name Frontend --spa

      - name: Start Backend with PM2
        working-directory: ./backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: pm2 start ./server.js --name backend --update-env --cwd "$PWD"

      - name: Save PM2 state
        run: pm2 save
