name: Backend CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30
    environment:
      name: MONGO_URI

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack (Yarn)
        run: |
          set -e
          corepack enable
          corepack prepare yarn@1.22.22 --activate
          yarn --version

      - name: Ensure PM2
        run: |
          command -v pm2 || npm i -g pm2
          pm2 -v

      # ---- Backend ----
      - name: Create backend .env from secrets
        working-directory: ./backend
        run: |
          set -euo pipefail
          : > .env
          printf "MONGO_URI=%s\n" "${{ secrets.MONGO_URI }}" >> .env
          printf "JWT_SECRET=%s\n" "${{ secrets.JWT_SECRET }}" >> .env
          printf "PORT=%s\n"       "${{ secrets.PORT }}"       >> .env
          awk -F= '{print "KEY:", $1}' .env
          grep -qE '^MONGO_URI=.+$' .env || { echo "MONGO_URI is empty"; exit 1; }

      - name: Install backend deps
        working-directory: ./backend
        run: yarn install --frozen-lockfile

      - name: Run backend tests (optional)
        working-directory: ./backend
        env:
          NODE_ENV: test
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: yarn test --if-present

      # ---- Frontend ----
      - name: Install frontend deps
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Build frontend
        working-directory: ./frontend
        run: yarn build

      # ---- Deploy  ----
      - name: Switch apps with PM2
        run: |
          set -e
          # Frontend
          pm2 describe Frontend >/dev/null 2>&1 && pm2 reload Frontend \
            || pm2 serve ./frontend/build 3000 --name Frontend --spa

          # Backend
          cd backend
          pm2 describe backend >/dev/null 2>&1 && pm2 reload backend --update-env \
            || pm2 start ./server.js --name backend --update-env --cwd "$PWD"
          pm2 save

      # ---- Health checks ----
      - name: Health check backend
        run: curl -sfI http://127.0.0.1:${{ secrets.PORT || '5001' }} || (pm2 logs backend --lines 100; exit 1)
      - name: Health check frontend
        run: curl -sfI http://127.0.0.1:3000 || (pm2 logs Frontend --lines 50; exit 1)
